/* Generated by bin2c, do not edit manually */
#ifndef __certs_h_included
#define __certs_h_included

/* Contents of file swims_root_ca.pem */
#define swims_root_ca_pem_size 2078
extern const unsigned char swims_root_ca_pem[2078];

#endif    /* __certs_h_included */
